### ISSUE TITLE
Loading a chip, changes all other chips in area

### ISSUE THREAD

**Issue by samneub** [ThomasFooteDQ/DroidQuest#16] opened 2016-06-23 21:58 UTC
In the Innovation Lab, and sometimes else where, when I load a chip of particular type, all the other small chips in the area get the same type. I need to make a slower clock, but can't use it with an RSFlipFlop. I can just make it myself, but other chips will be such an amazing pain like this...

**Comment by FuzzyBoots** [comment] 2016-07-07 18:36
I can't replicate your issue. Have you made any modifications to the source code? Are you using a fork? Lastly, can you gives us a detailed list of steps you're taking, including whether you're using the keyboard or menus for each step?

**Comment by cognitivegears** [comment] 2016-10-29 01:44
Also unable to repro - closing since this has been open since Jun 23 without comment.  Please re-open if you are able to reproduce.

**Closed by cognitivegears** 2016-10-29 01:44 UTC
